# Generated by Django 3.2.4 on 2021-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matri', '0002_auto_20210913_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caste',
            field=models.CharField(choices=[('Rai', 'Rai'), ('Newar', 'Newar'), ('Brahmin', 'Brahmin'), ('Tamang', 'Tamang')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PHD', 'PHD'), ('Masters', 'Masters')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Businessman', 'Businessman'), ('Banker', 'Banker'), ('Teacher', 'Teacher')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.CharField(choices=[('40000 above', '40000 above'), ('20000-30000', '20000-30000'), ('30000-40000', '30000-40000'), ('less than 20000', 'less than 20000')], max_length=200),
        ),
        migrations.AlterField(
            model_name='requestprofile',
            name='caste',
            field=models.CharField(choices=[('Rai', 'Rai'), ('Newar', 'Newar'), ('Brahmin', 'Brahmin'), ('Tamang', 'Tamang')], max_length=200),
        ),
        migrations.AlterField(
            model_name='requestprofile',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PHD', 'PHD'), ('Masters', 'Masters')], max_length=200),
        ),
        migrations.AlterField(
            model_name='requestprofile',
            name='salary',
            field=models.CharField(choices=[('40000 above', '40000 above'), ('20000-30000', '20000-30000'), ('30000-40000', '30000-40000'), ('less than 20000', 'less than 20000')], max_length=200),
        ),
    ]
